package com.consumed.medicalconsulting.models.Enums;


public enum Specialization {
    ANESTESIOLOGÍA_Y_REANIMACIÓN,
    CIRUGÍA_GENERAL,
    CIRUGÍA_PEDIÁTRICA,
    CIRUGÍA_PLÁSTICA,
    CUIDADO_INTENSIVO,
    DERMATOLOGÍA,
    ENDOCRINOLOGÍA,
    GASTROENTEROLOGÍA,
    GERIATRÍA,
    HEMATOLOGÍA,
    INFECTOLOGÍA,
    MEDICINA_FÍSICA_Y_REHABILITACIÓN,
    MEDICINA_INTERNA,
    NEUMOLOGÍA_CLÍNICA,
    NEUROCIRUGIA,
    NEUROLOGÍA_CLÍNICA,
    NEUROPEDIATRÍA,
    OBSTETRICIA_Y_GINECOLOGÍA,
    OFTALMOLOGÍA,
    ONCOHEMATOLOGÍA_PEDIÁTRICA,
    ORTOPEDIA_Y_TRAUMATOLOGÍA,
    OTORRINOLARINGOLOGÍA,
    PATOLOGÍA_ANATÓMICA_Y_CLÍNICA,
    PEDIATRÍA,
    PERINATOLOGÍA,
    PSIQUIATRÍA,
    RADIOLOGÍA_E_IMÁGENES_DIAGNÓSTICAS,
    RADIOLOGÍA_PEDIÁTRICA,
    REUMATOLOGÍA,
    UROLOGÍA

}
